### ISSUE TITLE
侧滑和刷新存在bug

### ISSUE THREAD

**Issue by NewHuLe** [licaomeng/Android-PullToRefresh-SwipeMenuListView-Sample#1]
当侧滑没有关闭的时候，刷新经常出现无法下拉的情况，能否改进，或者侧滑的时候不让他下拉刷新

**Comment by licaomeng** [comment]
非常感谢你的反馈。我看了一下，估计你遇到的状况，是因为列表没有回到最顶部引起的。后来我又考虑了一下你的建议，觉得很有道理。如果在侧滑的过程当中，同时又出现了用户本不期望下拉的操作，这样会给用户造成一种很不稳定的感受，这是一种非常糟糕的用户体验。现在我已将代码更新，侧滑的时候，不会同时出现下拉操作。再次感谢你的建议！

**Comment by NewHuLe** [comment]
非常感谢你的改进，很好。如果你是追求视觉上完美的人，还有一个小建议：侧滑的时候不要让列表滚动，不知道做起来是否方便，其实就是类似QQ的刷新和侧滑效果，当然你这个已经做得很好了，多谢你的分享

**Comment by NewHuLe** [comment]
其实，刚测了一下，还是有那个无法下拉刷新的bug，你可以测测，就是多点点侧滑和刷新就会发现，不知道什么原因引起的，还请大神解决啊

**Comment by licaomeng** [comment]
请问这个bug，你是指当侧滑完全打开的时候，下拉刷新无效吗?

**Comment by NewHuLe** [comment]
一般都是触发侧滑关闭以后，无法刷新，就是没法下拉

**Comment by licaomeng** [comment]
Hi, 你再看一下吧，我这里测了一些应该没有什么问题了。问题的原因如下：
之前的代码是这样的，
if ((mFooterView.getBottomMargin() > 0 || deltaY < 0)) {
            // last item, already pulled up or want to pull up.
            updateFooterHeight(-deltaY / OFFSET_RADIO);
        } else if (getFirstVisiblePosition() == 0 && (mHeaderView.getVisiableHeight() > 0 || deltaY > 0)) {
            // the first item is showing, header has shown or pull down.
            updateHeaderHeight(deltaY / OFFSET_RADIO);
            invokeOnScrolling();
        }
当你侧滑的时候，如果deltaY < 0，（deltaY <0代表手指在Y方向上向下），那么就会进入第一个if里面，执行updateFooterHeight(-deltaY / OFFSET_RADIO); 这样mFooterView.getBottomMargin()的值就会被设置成>0的，那么当你再下拉的时候，依然是进入到第一个if，而不会进入else if 执行下拉的相关操作。这里我把两个if互换了一下位置，如下，
 if (getFirstVisiblePosition() == 0 && (mHeaderView.getVisiableHeight() > 0 || deltaY > 0)) {
                    // the first item is showing, header has shown or pull down.
                    updateHeaderHeight(deltaY / OFFSET_RADIO);
                    invokeOnScrolling();
                } else if ((mFooterView.getBottomMargin() > 0 || deltaY < 0)) {
                    // last item, already pulled up or want to pull up.
                    updateFooterHeight(-deltaY / OFFSET_RADIO);
                }

**Comment by NewHuLe** [comment]
好的，谢谢

**Comment by licaomeng** [comment]
Hi 之前你提出的那个改善体验的建议，就是侧滑的时候不会出现列表滚动的情况，我也解决了。Math.pow(dx, 2) / Math.pow(dy, 2) <= 3
加了上面这个判断，如果侧滑角度的水平夹角大于0°小于30°那么就侧滑，反之，下拉上拉。
